server:
  port: 8080

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml

spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
    devtools:
      restart:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    encoding: utf-8
    cache: false
    mode: html5




